// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BreakPointController from "./break_point_controller"
application.register("break-point", BreakPointController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
